export { default as Experience } from './Experience/Experience'
export { default as Footer } from './Footer/Footer'
export { default as Work } from './Work/Work'
export { default as Skills } from './Skills/Skills'
export { default as Hero } from './Hero/Hero'
export { default as Testimonial } from './Testimonial/Testimonial'